### PR TITLE
Add configuration option for log types

### PR DESCRIPTION
**Pull request by abunashir**
This commit adds a configuration option for log types, so a user can specify they log level they expect, and if they don't specify anything then by default relaton will display warnings or errors.

If you want to set a custom configuration option, then you can add the following line after initialization or as initializer

```ruby
Relaton.configuration.logs = [:info, :warn, :error]
```

Related: https://github.com/relaton/relaton-cli/issues/66

### CODE REVIEW

**Comment by abunashir** [comment]
I don't think the appveyor failures are related to this PR. Since GitHub CI is already testing this in windows, should we disable appveyor from this repo? @ronaldtse

**Comment by andrew2net** [comment]
@abunashir Appveyor should be disabled. I don't have access to do it. Please disable it if you have access.

**Comment by abunashir** [comment]
Thanks, I don't have access for the relaton organization either, @ronaldtse: could you please help us out here to disable the AppVeyor for this repo?

**Comment by ronaldtse** [comment]
@abunashir @andrew2net I've just removed all relaton gems from AppVeyor. Merging.

**Comment by andrew2net** [comment]
@abunashir could you add test for these lines?
image

**Comment by ronaldtse** [comment]
Moved @andrew2net 's request to #72.

**Pull request merged**
